name: Build Android Debug APK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Unzip project
        run: unzip -o MultiAIStarter.zip -d src

      - name: Ensure Gradle Wrapper (if missing)
        run: |
          if [ ! -f src/gradlew ]; then
            sudo apt-get update
            sudo apt-get install -y gradle
            cd src
            gradle wrapper --gradle-version 8.4.2
          fi
          chmod +x src/gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace --no-daemon
        working-directory: src

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: src/app/build/outputs/apk/debug/*.apk