name: Build Android Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # გააფუთე შენი პროექტი სამუშაო საქაღალდეში
      - name: Unzip project
        run: unzip MultiAIStarter.zip -d src

      # მოვამზადოთ Gradle (თუ wrapper არაა, მოგვეწოდება gradle ბინარი)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.7"

      # გენერაცია: wrapper ფაილები (gradlew და gradle/wrapper/*)
      - name: Generate Gradle wrapper
        run: |
          cd src
          gradle wrapper --gradle-version 8.7

      - name: Make gradlew executable
        run: chmod +x src/gradlew

      # Build
      - name: Build with Gradle
        run: |
          cd src
          ./gradlew assembleDebug

      # Artifact upload (გადაამოწმე ბილდის გზა თუ სხვა მოდულია)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: src/app/build/outputs/apk/debug/app-debug.apk