name: Build Android Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Install Gradle CLI (and unzip)
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle zip unzip
          gradle --version

      - name: Unzip project
        run: unzip -o MultiAIStarter.zip -d src

      - name: List src (sanity check)
        run: ls -la src

      - name: Generate Gradle wrapper
        working-directory: src
        run: gradle wrapper --gradle-version 8.4

      - name: Make gradlew executable
        working-directory: src
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: src
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            src/**/build/outputs/apk/**/debug/*.apk